### ISSUE TITLE
solution of banded linear systems

### ISSUE THREAD

**Issue by gasagna** [ApproxFun/BandedMatrices.jl#3]
Hi,
 
I almost got close to reinventing the wheel, but then had a look on METADATA and found this very interesting package.

In my work, I need to solve a banded system of equation. If you do not mind, I would like to contribute this functionality and open a WIP PR, so that you can track the progress and comment.

Thanks,

Davide

**Comment by dlfivefifty** [comment]
Great! Make sure you are on master, as there's been a substantial rewrite.  I'll tag a new version shortly

**Comment by gasagna** [comment]
After a first investigation, I discovered that the banded LU factorisation lapack routines wrapped in julia require the storage to have `2*l + u + 1` rows for a matrix with upper/lower bandwidth `u/l` (gbtrf! and gbtrs! at https://github.com/JuliaLang/julia/blob/v0.4.5/base/linalg/lapack.jl#L69). This is because row interchanges due to pivoting in the factorisation increase the bandwidth (see e.g. dgbtrf/dgbtrs http://www.netlib.org/lapack/explore-html-3.4.2/d2/d2d/group__double_g_bcomputational.html#)
Currently, the storage in this package only covers the nonzero bands (`l+u+1`) so a pivoted factorisation cannot be computed in place, but a data copy into a larger array (`l` more rows) is necessary. 

Now, I do not known how difficult it is to change the underlying storage in this package to suit the lapack routines. Most importantly, it depends on whether you think this is something that you would like to have in the package. 

If one does not need to solve linear systems, the additional storage is a waste of space. One could have a constructor with an extra option `storage::Symbol=:compact`, turned on by default, that can be modified to `:lapack` when a factorisation is required.

**Comment by dlfivefifty** [comment]
I think for now it's best to implement it by copying. If that turns out to be too expensive, we can rethink the storage.
