### ISSUE TITLE
`setindex` issue

### ISSUE THREAD

**Issue by gasagna** [ApproxFun/BandedMatrices.jl#5]
Consider this

```julia
julia> a = bones(5, 5, 1, 1)
5x5 BandedMatrices.BandedMatrix{Float64}:
 1.0  1.0
 1.0  1.0  1.0
      1.0  1.0  1.0
           1.0  1.0  1.0
                1.0  1.0

julia> a[1, 1:2] = 2
ERROR: BoundsError
 in setindex! at /Users/davide/Software/BandedMatrices.jl/src/BandedMatrices.jl:243
````

The BoundsError is actually taking place at https://github.com/ApproxFun/BandedMatrices.jl/blob/master/src/BandedMatrices.jl#L245.

I can prepare a PR.

**Comment by dlfivefifty** [comment]
If you prepare a PR that would be great!


PS I was looking around and “band matrix” seems more common than “banded matrix”.  Any thoughts on renaming it “BandMatrices.jl” and the type “BandMatrix”?

PPS I have use for a “BandedTensor” type.  Any thoughts on adding this to the package?

**Comment by gasagna** [comment]
I am studying julia indexing code to come up with something good.

PS: OK for BandMatrices - it is also shorter
PPS: Sure! Then "BandTensors.jl" would be more appropriate. It depends on the usage that people will do of this package. In my case I have band linear systems, so the extension to tensors will not be so useful.

**Comment by MikaelSlevinsky** [comment]
-1 to BandMatrices. Banded is an adjective like triangular or unitary.

Cheers,

Mikael

**Comment by marcusdavidwebb** [comment]
On the terminology front, sometimes it can be informative to use Google 
Trends. Of course, there can still be nothing better than to see what 
people are saying in the literature.

It appears that Band Matrix is more popular by searches overall, but 
restricted to Computer Science related searches (however Google decides 
that...), Banded Matrix is slightly more popular. In Mathematics, 
apparently Band Matrix is again more popular.

All the search data appears to come from the US, btw. As an Englishman 
I'm inclined towards Banded Matrix, but Band Matrix is shorter.

https://www.google.co.uk/trends/explore#q=band%20matrix%2C%20banded%20matrix&cmpt=q&tz=Etc%2FGMT-1

https://www.google.co.uk/trends/explore#cat=0-174-1227&q=band%20matrix%2C%20banded%20matrix&cmpt=q&tz=Etc%2FGMT-1

https://www.google.co.uk/trends/explore#cat=0-174-436&q=band%20matrix%2C%20banded%20matrix&cmpt=q&tz=Etc%2FGMT-1

Cheers,
Marcus

**Comment by gasagna** [comment]
I have done some work on overloading `setindex` and came up with few ideas for the api. Here are a few examples of what I though would be a good way to go

````julia
a[k, 6] = 1 # row k column 6- error if (k, 6) is not in band
a[k, 1:3] = 1 # row k columns 1:3 - error if 1:3 out of band
a[k, bandrange(k)] = 1 # all in-band elements at row k
a[k, :] =  1 # error unless full bandwidth -> raise error in constructor "consider using full"
a[band(3),  :]  = 1 # all elements in band 3
a[band(0),  :]  = 1 # all elements along the diagonal
a[band(-1), :]  = 1 # all elements in the lower diagonal
a[band(0), 1:3]  = 1 # first three element on the diagonal 
a[:, :]  = 1 # error
````

Comments welcome!
